{# 
    This template is used to generate SPARQL INSERT DATA queries.
    The template takes two parameters:
    - raw_triples: the data to be inserted
    - context: the context in which the data should be inserted
#}

{% if context %}
INSERT DATA { GRAPH <{{ context }}> { {{ raw_triples }} } }
{% else %}
INSERT DATA { {{ raw_triples }} }
{% endif %}